name: Deploy to EC2 (Docker run)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  id-token: write   # for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- Auth in GitHub runner (to push to ECR) ---
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      # --- Build & push image to ECR ---
      - name: Build and push image
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
          REPO: ${{ secrets.ECR_REPOSITORY }}
          TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPO:$TAG .
          docker tag  $REGISTRY/$REPO:$TAG $REGISTRY/$REPO:latest
          docker push $REGISTRY/$REPO:$TAG
          docker push $REGISTRY/$REPO:latest

      # --- SSH into EC2 and run container (EC2 has Instance Role: ECR ReadOnly) ---
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -euo pipefail
            REGION=${{ secrets.AWS_REGION }}
            ACCOUNT=${{ secrets.AWS_ECR_ACCOUNT }}
            REPO=${{ secrets.ECR_REPOSITORY }}
            IMAGE="$ACCOUNT.dkr.ecr.$REGION.amazonaws.com/$REPO:latest"

            # ECR login (uses EC2 instance role)
            aws ecr get-login-password --region "$REGION" \
              | docker login --username AWS --password-stdin "$ACCOUNT.dkr.ecr.$REGION.amazonaws.com"

            sudo mkdir -p /srv/app
            docker pull "$IMAGE"
            docker rm -f "$REPO" || true
            docker run -d --name "$REPO" \
              --restart unless-stopped \
              --env-file /srv/app/.env \
              -p 80:3000 \
              "$IMAGE"

            docker image prune -f
